# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyuOCjW1fbk6lV9Aj_cHqrh-ueMc7aDG
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Título
st.set_page_config(page_title="Dashboard Mercado Livre - Notebooks", layout="wide")
st.title("💻 Dashboard - Notebooks Mercado Livre")
st.markdown("Análise de preços de notebooks com dados coletados automaticamente via scraping.")

# Carregar dados
@st.cache_data
def carregar_dados():
    return pd.read_csv("../notebooks_mel.csv")

df = carregar_dados()

# Tratar possíveis colunas extras
df.columns = [col.strip().lower().replace(" ", "_") for col in df.columns]

# Filtros
marcas = df["marca"].dropna().unique()
marca_selecionada = st.sidebar.multiselect("Filtrar por marca", sorted(marcas), default=sorted(marcas))

df_filtrado = df[df["marca"].isin(marca_selecionada)]

# Gráfico 1: Preço médio por marca
preco_medio = df_filtrado.groupby("marca")["preco"].mean().reset_index()
fig1 = px.bar(preco_medio, x="marca", y="preco", title="💰 Preço Médio por Marca", text_auto='.2s')
fig1.update_layout(xaxis_title="Marca", yaxis_title="Preço (R$)", template="plotly_white")

# Gráfico 2: Distribuição de preços
fig2 = px.histogram(df_filtrado, x="preco", nbins=30, title="📊 Distribuição de Preços")
fig2.update_layout(xaxis_title="Preço (R$)", yaxis_title="Quantidade", template="plotly_white")

# Gráfico 3: Preço por título (Top 20 mais caros)
top20 = df_filtrado.sort_values(by="preco", ascending=False).head(20)
fig3 = px.bar(top20, x="preco", y="titulo", orientation="h", title="🏷️ Top 20 Notebooks Mais Caros", text_auto='.2s')
fig3.update_layout(xaxis_title="Preço (R$)", yaxis_title="Título", template="plotly_white")

# Layout
col1, col2 = st.columns(2)
col1.plotly_chart(fig1, use_container_width=True)
col2.plotly_chart(fig2, use_container_width=True)

st.plotly_chart(fig3, use_container_width=True)